### PR TITLE
Add bedrock support

### PR DESCRIPTION
**Pull request by extremeheat**
* Also add some tests

### CODE REVIEW

**Comment by u9g** [comment]
for this to be merged, either we have to move to node15 or you need to get rid of the `??=`

**Comment by extremeheat** [comment]
work here is also blocked by nmd PR

**Comment by rom1504** [comment]
nmd pr is merged

**Comment by rom1504** [comment]
could this be revisited now?

**Comment by extremeheat** [comment]
Yeah, next week I'll work on the inventory and physics part after 1.18.0 chunks are fully implemented. Right now there's no way to test this in game, especially to handle the edge cases with things like cakes for example. Should be possible to have a good testing apparatus once inventory is implemented.

**Comment by rom1504** [comment]
feel free to re open

**Pull request closed without merging**
