### PR TITLE
Fix upside-down recipes

### LINKED ISSUE #1112: Server rejects Transaction while Crafting
[X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.22.0
 - server: spigot 1.15.2
 - node: 14.3.0

## Detailed description of a problem
The Server rejects the Transaction while crafting a Iron Axe.

## Current code
```js
crafting_bench = bot.blockAt(v(-12,60,-151)) // Crafting Bench
iron_axe_recipe = bot.recipesFor(522,null,1,crafting_bench)[0] // First Recipe for a iron_axe
bot.craft(iron_axe_recipe,1,crafting_bench,(err)=>{
    console.log(err)
})
```

## Expected behavior
It should not reject the Transaction and craft the iron axe.

## Additional context
I don't know if it's relevant but i get the items from a chest first. That should not interfere with crafting though. I've read through some of the fixed Issues and they all seemed that they got fixed by adding a delay. This sadly did not fix my Problem. 

I have provided the Recipe incase it helps debugging.
```js
Recipe {
  result: RecipeItem { id: 522, metadata: undefined, count: 1 },
  inShape: [
    [ [RecipeItem], [RecipeItem] ],
    [ [RecipeItem], [RecipeItem] ],
    [ [RecipeItem], [RecipeItem] ]
  ],
  outShape: null,
  ingredients: null,
  delta: [
    RecipeItem { id: 545, metadata: null, count: -2 },
    RecipeItem { id: 530, metadata: null, count: -3 },
    RecipeItem { id: 522, metadata: undefined, count: 1 }
  ],
  requiresTable: true
}
```

### PR DESCRIPTION
**Pull request by Slord6**
Resolves https://github.com/PrismarineJS/mineflayer/issues/1112

### CODE REVIEW

**Comment by rom1504** [comment]
Is this correct for all versions ?

**Comment by Slord6** [comment]
Just tested and no it isn't.
`1.12.2` requires the prior version.
`1.13.*` I can't get crafting to work in to test. For `1.13` on crafting I get an error of `missing ingredient` for a chest when the bot has oak planks, and the same for crafting a hopper when the bot has chests and iron ingots. So, not sure what's happening there but it looks unrelated as it happens with whichever both my code and the prior version. `1.13.2` however works fine and requires the new version.
`1.14.2` requires the new version.
I guess the change happened in `1.13` so I've added in the check for then

**Comment by rom1504** [comment]
I think the correct fix is to change the data, not to change the reading code.
Either reverse the previous recipes or the new ones

**Comment by Slord6** [comment]
So is that a change that need to happen in [minecraft-data](https://github.com/PrismarineJS/minecraft-data)?

**Comment by rom1504** [comment]
Yes

**Comment by Slord6** [comment]
Closing as not the right project for this change as per discussion above

**Pull request closed without merging**
